export const ROUTES = {
    HOME: `/`, 
    LOG_IN: "/login",
    REGISTER: "/register",
    CAR_DETAILS:`/cars/car`,
    USER_DETAILS:"/users/user",
    HELP_PAGE:"/help",
    HELP_CENTER:"/help/helpcenter",
    SETTINGS:"/settings",
    ADD_CAR:'/cars/car/add',
    EDIT_CAR:'/cars/car/edit',
    MY_PROFILE:'/users/myprofile',
    PRIVACY_AND_SECURITY:'/help/privacyandsecurity',
    REPORT_PROBLEM:'/help/reportproblem',
    SAVED_ARTICLES:'/users/myprofile/articles',
    SAVED_SEARCHES:'/users/myprofile/searches',
    CAR_LIST:'/users/myprofile/searches/carList',
    ADMIN_HOME:'/admin/home',
    ADMIN_DASHBOARD:'/admin/dashboard',
    ADD_USER:'/admin/dashboard/addUser'
};